name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenche le workflow pour les tags comme v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Spécifiez la version de Python

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install requests pandas validators packaging

      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=LinkTesterApp main.py

      - name: Install Inno Setup
        uses: johannesjo/setup-innosetup@v1
        with:
          version: '6.2.0'  # Spécifiez la version d'Inno Setup

      - name: Build installer with Inno Setup
        run: |
          iscc setup.iss

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: LinkTesterApp-Installer
          path: setup_LinkTesterApp_*.exe

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: setup_LinkTesterApp_${{ github.ref_name }}.exe
          asset_name: setup_LinkTesterApp_${{ github.ref_name }}.exe
          asset_content_type: application/octet-stream
