name: Build and Release

permissions:
  contents: write
  releases: write

on:
  push:
    tags:
      - 'v*.*.*'  # Déclenche le workflow pour les tags comme v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2 : Lister le contenu du répertoire pour le débogage
      - name: List directory contents
        run: |
          echo "Listing root directory:"
          dir
          echo "Listing .github/workflows directory:"
          dir .github\workflows
          echo "Listing Output directory:"
          dir Output
          echo "Listing dist directory:"
          dir dist

      # Étape 3 : Configuration de Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Spécifiez la version de Python

      # Étape 4 : Installation des dépendances
      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install requests pandas validators packaging

      # Étape 5 : Construction de l'exécutable avec PyInstaller
      - name: Build executable with PyInstaller
        run: |
          pyinstaller --onefile --name=LinkTesterApp LinkTesterApp.py

      # Étape 6 : Installation de Chocolatey
      - name: Install Chocolatey
        shell: powershell
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          [System.Net.ServicePointManager]::SecurityProtocol = `
            [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
          iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

      # Étape 7 : Installation d'Inno Setup via Chocolatey
      - name: Install Inno Setup
        shell: powershell
        run: |
          choco install innosetup -y

      # Étape 8 : Construction de l'installateur avec Inno Setup
      - name: Build installer with Inno Setup
        shell: cmd
        run: |
          "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" setup.iss

      # Étape 9 : Vérifier la présence de l'installateur
      - name: Verify installer creation
        run: |
          if exist setup_LinkTesterApp.exe (
            echo "Installer found."
          ) else (
            echo "Installer not found."
            exit 1
          )

      # Étape 10 : Extraire la version sans le préfixe 'v'
      - name: Extract version
        id: extract_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # Étape 11 : Renommer l'installateur pour inclure la version
      - name: Rename installer to include version
        shell: cmd
        run: |
          copy setup_LinkTesterApp.exe setup_LinkTesterApp_${{ env.version }}.exe

      # Étape 12 : Upload de l'installateur en tant qu'artefact (optionnel)
      - name: Upload installer as artifact
        uses: actions/upload-artifact@v3
        with:
          name: LinkTesterApp-Installer
          path: setup_LinkTesterApp_${{ env.version }}.exe

      # Étape 13 : Création de la Release GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false

      # Étape 14 : Upload de l'installateur en tant qu'Asset de la Release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: setup_LinkTesterApp_${{ env.version }}.exe
          asset_name: setup_LinkTesterApp_${{ env.version }}.exe
          asset_content_type: application/octet-stream
